[tool.poetry]
name = "tony-bot"
version = "0.1.0"
description = ""
authors = ["Marvelman3284 <jedimaster3284@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
discord = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
